#ifndef SHARE_IOCTL_H
#define SHARE_IOCTL_H

#include <ntifs.h>

/*

	IOCTL CODEs 

	For IOCTL Command works

*/
#define IOCTL_NEWSCAN \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1651, METHOD_BUFFERED, FILE_ANY_ACCESS) // NewScan ( First ) 

#define IOCTL_TARGETSCAN \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1652, METHOD_BUFFERED, FILE_ANY_ACCESS) // NextScan ( Address & value Match ) 

#define IOCTL_MEMDUMP \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1653, METHOD_BUFFERED, FILE_ANY_ACCESS) // Memory Page Dump

#define IOCTL_DLLINJECTION \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1654, METHOD_BUFFERED, FILE_ANY_ACCESS) // DLL Injection

#define IOCTL_HardwareBP \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1655, METHOD_BUFFERED, FILE_ANY_ACCESS) // HardWare BP

#define IOCTL_MEMWRITE \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1656, METHOD_BUFFERED, FILE_ANY_ACCESS) // Memory Write

#define IOCTL_MEMALLSCAN \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1657, METHOD_BUFFERED, FILE_ANY_ACCESS) // Memory ALL SCAN 

#endif